### ISSUE TITLE
More accurate y axis ticks

### ISSUE THREAD

**Issue by svetter** [aantn/smag#13]
Hi,

I noticed that ticks on the y axis aren't really placed accurately, as a result of the interface with `tui::widgets::Chart` and having a fixed number of ticks, as demonstrated here:

![image](https://github.com/aantn/smag/assets/39708242/6f6039ae-1284-4f5e-bac3-26b725b3291f)

**I have started to work on a fix for this**, in fact I think I'm almost done, but this is my first time working with Rust and I have a problem which I think is quicker to solve if I just ask you:

### My problem

Between the calls to `y_axis_bounds()` and `y_axis_labels()`, I need to store the number of y axis ticks, which is now dynamically calculated in `y_axis_bounds()`. More specifically, I need to store an int in `y_axis_bounds()` and read it from `y_axis_labels()`. Where should I store this value?

I thought adding a member to the `struct DataStore` would be the obivous way to do this but that just leads me down a path of mutability issues, which would probably take me hours to solve since I don't really have an overview of the whole codebase. I imagine you know where to store the value right away, so if that is the case, I'd be grateful for a quick pointer.

Thanks!

**Comment by aantn** [comment]
No quick advice, its been some time since I touched the code myself. Feel free to open a PR

**Comment by svetter** [comment]
Alright, I'll have another look and commit my WIP if I can't figure it out.
