### ISSUE TITLE
Extracting numbers

### ISSUE THREAD

**Issue by brentstewart** [aantn/smag#3]
I think this is just my lack of sophistication, but I'm trying to graph a number that is extracted from a text block and it's not working.  For example, this produces a float: 
> ./smag "ping -c 1 -R 8.8.8.8 | grep time= | awk '{print $7}' | cut -c 6-"
and this produces an integer:
> ./smag "ping -c 1 -R 8.8.8.8 | grep time= | awk '{print $7}' | cut -c 6-7"
but neither produces a graph.
Yes, I realize this reproduces gping :), but a lot of commands produce a block of text with embedded numbers.  Thanks for your help!

**Comment by aantn** [comment]
Thank you for the bug report. Try replacing `$7` with `\$7` in the awk command. For me that fixes the issue. Bash is replacing $7 because it is in a string.

**Comment by brentstewart** [comment]
That was it!  Thanks for your help!
