### ISSUE TITLE
Cargo.lock needs to be updated but --locked was passed to prevent this

### ISSUE THREAD

**Issue by fryfrog** [aantn/smag#4]
Something about the v0.5.3 release does not like building with `--locked`, but the tip of `main` is fine w/ it. I'm trying to create an AUR package for Arch Linux and they like that option for reproducible builds. I'm not very familiar w/ rust building or rust packaging, so I'm just kind of messing around.

```
0 ✓ fryfrog@apollo ~/git/smag $[main] git checkout tags/v0.5.3 -b v0.5.3
Switched to a new branch 'v0.5.3'
0 ✓ fryfrog@apollo ~/git/smag $[v0.5.3] cargo build --release --locked --all-features --target-dir=target
error: the lock file /home/fryfrog/git/smag/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, use the --offline flag.
```

```
101 ✗ fryfrog@apollo ~/git/smag $[v0.5.3] git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
0 ✓ fryfrog@apollo ~/git/smag $[main] cargo build --release --locked --all-features --target-dir=target
   Compiling libc v0.2.80
   Compiling proc-macro2 v1.0.24
   Compiling version_check v0.9.2
   Compiling cfg-if v0.1.10
   Compiling unicode-xid v0.2.1
   Compiling log v0.4.11
   Compiling bitflags v1.2.1
```

**Comment by fryfrog** [comment]
Works fine in 0.5.4. Thanks for fixing! :)

**Comment by aantn** [comment]
No problem. Didn't have time to verify that my fix worked yet. Glad to hear it solved the problem.

**Comment by fryfrog** [comment]
This is happening again in 0.8.0, can you give it a look again?

**Comment by aantn** [comment]
Sorry, smag is in maintenance mode at the moment. I have time to review PRs but not actively work on fixing problems myself. So if someone opens a PR I can review, but I do not recall how I fixed last time.
