### ISSUE TITLE
Support for y-axis unit label(s)

### ISSUE THREAD

**Issue by bermudalocket** [aantn/smag#6]
E.g., `smag --y-label=MB ...`

My motivation for this suggestion comes from plotting the total number of transferred bytes during a Time Machine backup. My command is

`smag "tmutil status | awk '/bytes =/ {print \$3/1000000}' | sed 's/;//g'"`

which outputs the total number of transferred bytes in MB. However, sometimes when I use this command I change it to GB, especially if I'm doing a fresh backup to a new drive. For incremental backups MB is fine, but for fresh ones GB gives a better picture of the progress.

**Comment by aantn** [comment]
This has been implemented in version 0.6.0
